# Generated by Django 5.1.7 on 2025-05-30 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospitals', '0002_transaction'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
