# Generated by Django 5.1.7 on 2025-05-30 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0003_blooddonationrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='blooddonation',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
