# Generated by Django 5.1.7 on 2025-05-30 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0004_blooddonation_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blooddonation',
            name='status',
            field=models.CharField(choices=[('Pending', 'pending'), ('Appointed', 'appointed'), ('Completed', 'completed')], max_length=20),
        ),
    ]
